version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 7sO60k48i1h2359DtfYw
    ports:
      - "5432:5432"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
